modmap:
  - name: CapsLock -> Ctrl Left
    remap:
      CapsLock: Ctrl_L
  - name: Alt -> Super
    remap:
      Alt_L: Super_L
      Super_L: Alt_L
keymap:
  - name: Vim binding
    remap:
      C-h: { with_mark: left }
      C-j: { with_mark: down }
      C-k: { with_mark: up }
      C-l: { with_mark: right }
