modmap:
  - name: CapsLock -> Ctrl Left
    remap:
      CapsLock: Ctrl_L
  - name: Alt -> Super
    remap:
      Alt_L: Super_L
      Super_L: Alt_L
keymap:
  - name: Vim binding
    remap:
      C-h: Left
      C-j: Down
      C-k: Up
      C-l: Right
