import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[window]
startup_mode = "Maximized"
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "none"
opacity = 0.7
blur = true

[selection]
save_to_clipboard = true

[cursor]
style.blinking = "On"
