[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[window]
decorations = "none"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
